### ISSUE TITLE
Install QCloud test website to .23

### ISSUE THREAD

**Issue by rolivella** [proteomicsunitcrg/atlas#155]
Install an old java version: 

```bash
#JAVA (local for QCloud test version)
export PATH="/home/proteomics/mysoftware/java/jdk-11.0.2/bin:$PATH"
export LD_LIBRARY_PATH="/home/proteomics/mysoftware/java/jdk-11.0.2/lib:$LD_LIBRARY_PATH"
export JAVA_HOME="/home/proteomics/mysoftware/java/jdk-11.0.2"
```

Modify `application.yml`: 

```yml
qcloud:                                                                                 
    app-url: http://localhost
 spring:                                                                                 
   profiles: production                                                                  
   datasource:                                                                           
   ## MYSQL                                                                            
   url: jdbc:mysql://127.0.0.1:3306/qcloud                                             
   username: "xxx"                                                                    
   password: "xxx" 
```
To run it: 

`proteomics@hipnos6:~/mydata/jar$ java -jar QCloud2-latest.jar --spring.config.location=application.yml`
