### ISSUE TITLE
Adaptatition of DIANN branch to parquet

### ISSUE THREAD

**Issue by rolivella** [proteomicsunitcrg/atlas#308]
Current report.tsv: 
```
proteomics@makarov:~/mygit/atlas-runs/9bfd7ee6-f8cf-410a-886f-8bc1eea2748f/28/29688fe4f229e5aed4dd96aa5e61ff$ head 2025NK024_FCAN_008_01_5pto.report.tsv
File.Name	Run	Protein.Group	Protein.Ids	Protein.Names	Genes	PG.Quantity	PG.Normalised	PG.MaxLFQ	Genes.Quantity	Genes.Normalised	Genes.MaxLFQ	Genes.MaxLFQ.Unique	Modified.Sequence	Stripped.Sequence	Precursor.Id	Precursor.Charge	Q.Value	PEP	Global.Q.Value	Protein.Q.Value	PG.Q.Value	Global.PG.Q.Value	GG.Q.Value	Translated.Q.Value	Proteotypic	Precursor.Quantity	Precursor.Normalised	Quantity.Quality	RT	RT.Start	RT.Stop	iRT	Predicted.RT	Predicted.iRT	First.Protein.Description	Lib.Q.Value	Lib.PG.Q.Value	Ms1.Profile.Corr	Ms1.Area	Ms1.Normalised	Normalisation.Factor	Evidence	Spectrum.Similarity	Averagine	Mass.Evidence	CScore	Fragment.Quant.Raw	Fragment.Correlations	MS2.Scan	PTM.Informative	PTM.Specific	PTM.Localising	PTM.Q.Value	PTM.Site.Confidence	Lib.PTM.Site.Confidence	IM	iIM	Predicted.IM	Predicted.iIM
2025NK024_FCAN_008_01_5pto.mzML	2025NK024_FCAN_008_01_5pto	Q8N697	Q8N697	S15A4_HUMAN	SLC15A4	26809.2	26809.2	26809.2	26809.2	26809.2	26809.2	26809.2	AAAAAAAAGAFAGR	AAAAAAAAGAFAGR	AAAAAAAAGAFAGR2	2	0.00432553	0.0330837	0.00435348	0.00281917	0.00314342	0.00314342	0.00314961	0	1	26809.2	26809.2	0.626527	14.3892	14.2791	14.4443	9.84723	14.5622	13.096	Solute carrier family 15 member 4	0	0	0.228735	177152	177152	1	2.04316	0.232418	0.044282	0.482601	0.942381	738.53;1838.71;333.283;206.311;1150.39;1846.96;0;604.553;755.723;322.403;0;1265.55;	-0.0572227;0.589543;-0;0.0676208;0.512185;0.734564;0;0.245819;0.0676208;0.207574;0;0.373399;	157391	0.482601	0	0	00	1	0	0.927265	0	0
```

New with Apache Parquet: 

```
sudo apt install wget unzip
wget https://github.com/duckdb/duckdb/releases/download/v0.9.2/duckdb_cli-linux-amd64.zip
unzip duckdb_cli-linux-amd64.zip
chmod +x duckdb
sudo mv duckdb /usr/local/bin/
```

and

```
duckdb -c "SELECT * FROM 'fitxer.parquet' LIMIT 5"

```

**Comment by rolivella** [comment]
Last meeting with Cristina and Eduard: 
 
* New config files:  
   * Phospho NY Eva
   * LK SILAC: Proteome quantification (DIA) Cristina

* New parsing of phospho data (report.txt or tsv) -> 192  
* What are parametres 2.3.2 QCD1/QCD2? same for qsample i qcloud?

**Comment by rolivella** [comment]
Dev day 1: 

* Started YAML parsing and pipeline run according to this. 
* Now MK works. It should be tested QCD1.
* First new prompt to atlas diann refactor at Seqera AI: "Comprova altre cop als subworkflows si pels patterns QCD1 i QCD2 estan els mateixos canvis implementats per QC01 en tant al nou refactor de DIANN que empra el YAML a atlas-config/atlas-dev. Reclona aquests dos repos: la pipeline en dev és a https://github.com/proteomicsunitcrg/atlas/tree/feature/diann-refactor, i la seva configuració i paràmetres a https://github.com/proteomicsunitcrg/atlas-config/tree/main/atlas-dev. NO facis cap commit ni push sense demanar-me permís primer. Els canvis els faig jo. Explica-me'ls step by step i minimalista".
* Test all diann_methods_config.yaml
* starting from 2.2.0 no TRFP needed.

**Comment by rolivella** [comment]
Dev day 2: 
* Now QCD1 is working for both Thermo and Bruker. 
* Now: adaptation for versions > 1.9.2 to skip Thermo conversion.
   * Redesign spectral libs automatic recognition mechanism. Maybe with symlinks to original folders? 
   * Error to debug: `/users/pr/proteomics/mygit/atlas-runs/fafbe52f-9b4b-461f-9ec1-aaeed6d96a58/d2/f542c188c31a110693af89d1a81605`
```
[6:49] File #1/1
[6:49] Loading run 2026MK022_CRIS_002_01_1ul.raw
ThermoRaw exception: Instrument index not available for requested device (Parameter 'instrumentIndex')
Cannot read the metadata from the .raw file
ERROR: cannot load the file, skipping
ERROR: DIA-NN tried but failed to load the following files: 2026MK022_CRIS_002_01_1ul.raw
[6:52] Cross-run analysis
[6:52] Reading quantification information: 1 files
ERROR: cannot read the.quant file 2026MK022_CRIS_002_01_1ul.raw.quant
ERROR: empty .quant file
[6:57] Quantifying peptides
[6:57] Assembling protein groups
[6:57] Quantifying proteins
[6:57] Calculating q-values for protein and gene groups
[6:57] Calculating global q-values for protein and gene groups
[6:57] Protein groups with global q-value <= 0.01: 0
[6:57] Compressed report saved to 2026MK022_CRIS_002_01_1ul.report.parquet. Use R 'arrow' or Python 'PyArrow' package to process
[6:57] Site report saved to 2026MK022_CRIS_002_01_1ul.report.site_report.parquet
[6:57] Saving precursor levels matrix
[6:57] Precursor levels matrix (1% precursor and protein group FDR) saved to 2026MK022_CRIS_002_01_1ul.report.pr_matrix.tsv.
[6:57] Saving protein group levels matrix
[6:57] Protein groups matrix saved to 2026MK022_CRIS_002_01_1ul.report.pg_matrix.tsv.
[6:57] Saving gene group levels matrix
[6:57] Gene groups matrix saved to 2026MK022_CRIS_002_01_1ul.report.gg_matrix.tsv.
[6:57] Saving unique genes levels matrix
[6:57] Unique genes matrix saved to 2026MK022_CRIS_002_01_1ul.report.unique_genes_matrix.tsv.
[6:58] Manifest saved to 2026MK022_CRIS_002_01_1ul.report.manifest.txt
[6:58] Stats report saved to 2026MK022_CRIS_002_01_1ul.report.stats.tsv
[6:58] Generating spectral library:
[6:58] 0 precursors saved
[6:58] Spectral library saved to 2026MK022_CRIS_002_01_1ul.report-lib.parquet

The following warnings or errors (in alphabetic order) were detected at least the indicated number of times:
ERROR: DIA-NN tried but failed to load the following files: 2026MK022_CRIS_002_01_1ul.raw : 1
ERROR: cannot load the file, skipping : 1
ERROR: cannot read the.quant file 2026MK022_CRIS_002_01_1ul.raw.quant : 1
ERROR: empty .quant file : 1
WARNING: MBR turned off, at least two files are required : 1
WARNING: incorrect settings, the in silico-predicted library must be generated in a separate pipeline step and then used to process the raw data, now without activating FASTA digest : 1
WARNING: peptidoform scoring enabled because variable modifications have been declared; to disable, use --no-peptidoforms : 1
Finished
```

**Comment by rolivella** [comment]
Day 3, debug trfp true/false: 

```
cp /users/pr/data/orbitrap_astral1/Raw/2604/CRIS/2026NK022_CRIS_002_01_1ul.raw ~/mygit/atlas-incoming-dev/2026MK022_CRIS_002_01_1ul.raw.SP_Human

cd ~/mygit/atlas-runs; ~/mygit/atlas-dev/bin/trigger.sh crg prod ~/mygit/atlas-config/atlas-dev/assets
```

**Comment by rolivella** [comment]
Report Day 3 and Day 4:

* Implemented and tested new parameter for switching TRFP: `requiresConversion: true/false` at YAML.
* Implemented and tested new parameter for  deciding which spec. lib use with `diann_version` YAML. 
* Weekly synch between atlas-dev and atlas-test (code and config).
* Next: 
   * Implement and test `parser_version` at YAML. 
   * Fix harcode:
    ```
    # Conditional parameter configuration (hardcoded)
        pattern_sh="QCD1"
        param_name_sh="qvalue"
        param_value_sh="0.1"
    ```

**Comment by rolivella** [comment]
Days 5, 6 and 7 (of 10): 

* Implemented and tested parquet version. 
* Easter egg: remove mzML conversion 100% from diann.nf. Implementing a new R script using rawrr and testing.

**Comment by rolivella** [comment]
Day 8: 
* Leaved mzML conversion because of mzsniffer. 
* General test: 
   * QCD1 1.9.2 and 2.3.2. 
   * NK  2.3.2.
   * BK 2.3.2.

**Comment by rolivella** [comment]
atlas-test: 

QCD1 -> OK
NK -> OK
QC01 -> OK
MQ -> OK
QC02 -> OK
QCD2 -> OK
QCDE -> OK
QCHE -> ?

**Comment by rolivella** [comment]
Finished:  https://github.com/proteomicsunitcrg/atlas/releases/tag/v1.2.0

**Comment by rolivella** [comment]
```yaml
QCD1:
  diann_version: "1.9.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-1.9.2.img"  
  config_file: "diann_configs/diann_qcd1.cfg"
  parser_version: "tsv"
  executable: "/diann-1.9.2/diann-linux"
  description: "BSA DIA quality control"
  requiresConversion: true
  
QCD2:
  diann_version: "1.9.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-1.9.2.img"  
  config_file: "diann_configs/diann_qcd2.cfg"
  parser_version: "tsv"
  executable: "/diann-1.9.2/diann-linux"
  description: "HELA DIA quality control"
  requiresConversion: true                                            

NK:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_nk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome DIA quantification (current)"
  requiresConversion: false

MK:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_mk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome DIA quantification (old)"
  requiresConversion: false                                           

LD:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_ld.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Chromatin-bound proteome"
  requiresConversion: false   

ME:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_me.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome label-free quantification in exosomes (DIA) - Proteome"
  requiresConversion: false   

MS:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_ms.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome label-free quantification in secretome (DIA)"
  requiresConversion: false  

NY:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_ny.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Phosphoproteome label-free quantification (DIA)"
  requiresConversion: false  

BK:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img" 
  config_file: "diann_configs/diann_bk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome DIA quantification (Bruker)"
  requiresConversion: false                                            
```
